apiVersion: apps/v1
kind: Deployment
metadata:
  name: http1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http1
  template:
    metadata:
      labels:
        app: http1
    spec:
      containers:
      - name: http1
        image: unitedone/httptest
        args: ['10001','http1']
        ports:
        - containerPort: 10001
---
apiVersion: v1
kind: Service
metadata:
  name: http1
spec:
  selector:
    app: http1
  type: NodePort
  ports:
  - protocol: TCP
    port: 10001
